Traceback (most recent call last):
  File "/data/home/btx008/compchem-scripts/g09_UFF_input.py", line 39, in <module>
    cluster=rf.read_xyz(args.input)[-1]
  File "/data/home/btx008/cryspy/read_file.py", line 86, in read_xyz
    with open(in_name) as xyz_file:
IOError: [Errno 2] No such file or directory: '2hc_2_424-mega_UFF'
